# permissions for end users to edit nginxdeploys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nginx-operator
    app.kubernetes.io/managed-by: kustomize
  name: nginxdeploy-editor-role
rules:
- apiGroups:
  - app.app.example.com
  resources:
  - nginxdeploys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.app.example.com
  resources:
  - nginxdeploys/status
  verbs:
  - get
